<head>
<title>Research</title>
<meta name="Research projects of Guillaume Coqueret"/>
</head>

---
description: "Research projects of Guillaume Coqueret"
---

<br>  
<br>  


<style>
details > summary {
  padding: 9px;
  width: 100%;
  background-color: #ecf5ec;
  border: none;
  box-shadow: 1px 1px 2px #bbbbbb;
  cursor: pointer;
}

br2 {
  display: block; /* makes it have a width */
  content: ""; /* clears default height */
  margin-top: 0; /* change this to whatever height you want it */
}
</style>




### <font color="#9AAD98">**Ongoing research** (working papers)</font>  

- Overparametrized models with posterior drift (with M. Laguerre) <a href="https://arxiv.org/abs/2506.23619" target="_blank">[arXiv]</a>    
- Persistent anomalies and nonstandard errors (with C. Pérignon) <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5276723" target="_blank">[SSRN]</a>  
- Global p-values in multi-design studies (with Y. Zhang, C. Pérignon, F. Chiaromonte and S. Guerrier)   
- Incentives in corporate energy mix decisions (with B. Qiu)    
- Sustainable commodity factors (with B. Tavin and Y. Zhou) <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4698258" target="_blank">[SSRN]</a> <br> (Winner of the [cascad](https://www.cascad.tech/) best reproduced paper award at the [2024 AFFI conference](https://affi2024.eventsadmin.com/))     
- Factor investing with reinforcement learning (with E. André): <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3726714" target="_blank">[SSRN]</a>    
- Characteristics-driven returns in equilibrium: <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3941195" target="_blank">[SSRN]</a> - <a href="http://www.gcoqueret.com/files/misc/demand_6_share.html" target="_blank">R notebook</a>   
- Interactions in Asset Pricing (with G. Chevalier, M. Laguerre & T. Raffinot): <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4500944" target="_blank">[SSRN]</a>   



_____ 

### <font color="#9AAD98">**Main Publications**</font> 

The full list of articles can be found below.

* Unexpected opportunities in misspecified predictive regressions,  <br/> <span style="color:#3B60A2">**European Journal of Operational Research**</span> Vol. 318, No. 2 (2024), pp. 686-700 (with R. Deguest): <a href="https://www.sciencedirect.com/science/article/pii/S0377221724004235" target="_blank">[Link - Open Access]</a> - <a href="http://www.gcoqueret.com/PRs.html" target="_blank">material</a>    
* Procedural Rationality, Asset Heterogeneity and Market Selection,  <br/> <span style="color:#3B60A2">**Journal of Mathematical Economics**</span>, Vol. 82 (2019), pp. 125-149 (with B. Tavin) <a href="https://www.sciencedirect.com/science/article/abs/pii/S0304406819300205" target="_blank">[Link]</a>   <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2952659" target="_blank">[Working paper]</a>   <br/>
* Empirical properties of a heterogeneous agent model in large dimensions, <br/>   <span style="color:#3B60A2">**Journal of Economic Dynamics & Control**</span>, Vol. 77 (2017), pp. 180-201 <a href="https://www.sciencedirect.com/science/article/pii/S0165188917300386" target="_blank">[Link]</a>  
* Characteristics-based portfolio choice with leverage constraints, <br/>   <span style="color:#3B60A2">**Journal of Banking and Finance**</span>, Vol. 70 (2016), pp. 23-37 (with M. Ammann and J-P. Schade) <a href="https://www.sciencedirect.com/science/article/pii/S0378426616300516" target="_blank">[Link]</a> <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2736324" target="_blank">[Working paper]</a>   
* An investigation of model risk in a market with jumps and stochastic volatility, <br/>   <span style="color:#3B60A2">**European Journal of Operational Research**</span>, Vol. 253 (2016), pp. 648-658 (with B. Tavin) <a href="https://www.sciencedirect.com/science/article/abs/pii/S0377221716301461" target="_blank">[Link]</a>    <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2474223" target="_blank">[Working paper]</a>


_____ 

### <font color="#9AAD98">**Books**</font>

#### **Perspectives in sustainable equity investing**
CRC / Chapman Hall - March 2022   
Order on <a href="https://www.routledge.com/Perspectives-in-Sustainable-Equity-Investing/Coqueret/p/book/9781032071015" target="_blank">on the publisher's website</a>, <a href="https://www.amazon.fr/Perspectives-Sustainable-Investing-Guillaume-Coqueret/dp/103207101X/" target="_blank">Amazon (France)</a>, <a href="https://www.amazon.com/Perspectives-Sustainable-Investing-Guillaume-Coqueret-ebook/dp/B09RRMCB4R/" target="_blank">Amazon (US)</a>
or <a href="https://www.amazon.co.uk/Perspectives-Sustainable-Investing-Guillaume-Coqueret-ebook/dp/B09RRMCB4R/" target="_blank">Amazon (UK)</a>  
**Available**: <a href="http://www.esgperspectives.com" target="_blank">**open source website**</a> - <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3715753" target="_blank">Early working paper version</a>

#### **Machine learning for factor investing** (with T. Guida)
CRC / Chapman Hall, **R** version published in September 2020 - **Python** version published in September 2023    
Order the **R** version on <a href="https://www.routledge.com/Machine-Learning-for-Factor-Investing/Coqueret-Guida/p/book/9780367545864" target="_blank">on the publisher's website</a>, <a href="https://www.amazon.fr/Machine-Learning-Investing-Guillaume-Coqueret/dp/0367545861/" target="_blank">Amazon (France)</a>, <a href="https://www.amazon.com/Machine-Learning-Factor-Investing-Mathematics/dp/0367545861/ref=sr_1_1" target="_blank">Amazon (US)</a>
or <a href="https://www.amazon.co.uk/Machine-Learning-Investing-Financial-Mathematics/dp/0367545861/ref=sr_1_2" target="_blank">Amazon (UK)</a>   
**Available**: <a href="http://www.mlfactor.com" target="_blank">**open source website**</a> - <a href="https://github.com/shokru/mlfactor.github.io/tree/master/material" target="_blank">**Material**</a> - <a href="files/SLIDES/SLIDES.html" target="_blank">**Slides**</a>




_____ 

### <font color="#9AAD98">**Complete list of Published Academic Articles**</font> 

Articles are grouped into **research themes** below.

<details>
  <summary>**FINANCE & ECONOMICS**</summary>

* A note on implied correlation for bivariate contracts, <br/> <span style="color:#3B60A2">**Economics Bulletin**</span>, Vol. 40, No. 2 (2020), pp. 1388-1396 (with B. Tavin) <a href="http://www.accessecon.com/Pubs/EB/2020/Volume40/EB-20-V40-I2-P119.pdf" target="_blank">[Link]</a>   
* Procedural Rationality, Asset Heterogeneity and Market Selection,  <br/> <span style="color:#3B60A2">**Journal of Mathematical Economics**</span>, Vol. 82 (2019), pp. 125-149 (with B. Tavin) <a href="https://www.sciencedirect.com/science/article/abs/pii/S0304406819300205" target="_blank">[Link]</a>   <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2952659" target="_blank">[Working paper]</a>   <br/>
* Empirical properties of a heterogeneous agent model in large dimensions, <br/>   <span style="color:#3B60A2">**Journal of Economic Dynamics & Control**</span>, Vol. 77 (2017), pp. 180-201 <a href="https://www.sciencedirect.com/science/article/pii/S0165188917300386" target="_blank">[Link]</a>  
* An investigation of model risk in a market with jumps and stochastic volatility, <br/>   <span style="color:#3B60A2">**European Journal of Operational Research**</span>, Vol. 253 (2016), pp. 648-658 (with B. Tavin) <a href="https://www.sciencedirect.com/science/article/abs/pii/S0377221716301461" target="_blank">[Link]</a>    <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2474223" target="_blank">[Working paper]</a>
* Lookback option prices under a spectrally negative tempered-stable model, <br/>   <span style="color:#3B60A2">**International Journal of Theoretical and Applied Finance**</span>, Vol. 16, No. 3 (2013)  <a href="https://www.worldscientific.com/doi/abs/10.1142/S021902491350012X" target="_blank">[Link]</a>    

</details>

<br2>


<details>
  <summary>**SUSTAINABLE FINANCE**</summary>

* The biodiversity premium, <br/>
<span style="color:#3B60A2">**Ecological Economics**</span>, Vol. 228 (2025) (with T. Giroux & O.D. Zerbib): <a href="https://www.sciencedirect.com/science/article/pii/S092180092400332X" target="_blank">[Link - Open Access]</a> - <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4489550" target="_blank">SSRN</a>     
* ESG news spillovers across the value chain, <br/>
<span style="color:#3B60A2">**Financial Management**</span>, Vol. 52, No. 4 (2023), pp. 677-710 (with V. Le Tran) <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4002705" target="_blank">[Working Paper]</a>    
* Scopes of carbon emissions and their impact on green portfolios, <br/> <span style="color:#3B60A2">**Economic Modelling**</span>, Vol. 115 (2022), (with T. Anquetin, B. Tavin & L. Welgryn) <a href="https://www.sciencedirect.com/science/article/abs/pii/S0264999322001973" target="_blank">[Link]</a>  <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4012629" target="_blank">[Working Paper]</a>      

</details>

<br2>


<details>
  <summary>**DATA & DECISION SCIENCES**</summary>

* Unexpected opportunities in misspecified predictive regressions,  <br/> <span style="color:#3B60A2">**European Journal of Operational Research**</span> Vol. 318, No. 2 (2024), pp. 686-700 (with R. Deguest): <a href="https://www.sciencedirect.com/science/article/pii/S0377221724004235" target="_blank">[Link - Open Access]</a> - <a href="http://www.gcoqueret.com/PRs.html" target="_blank">material</a>   
* Dynamic decision making with predictive panels, <br/> <span style="color:#3B60A2">**Journal of the Operational Research Society**</span>, Vol. 75, No. 6 (2023), pp. 1055-1075 (with B. Tavin) <a href="https://www.tandfonline.com/doi/full/10.1080/01605682.2023.2231488" target="_blank">[Link]</a> <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3853793" target="_blank">[Working Paper]</a> - <a href="http://www.gcoqueret.com/files/misc/panel.html" target="_blank">[R notebook]</a>   
* The determinants of health assessment in the United States: A supervised learning approach, <br/> <span style="color:#3B60A2">**Healthcare Analytics**</span>, Vol. 2 (2022) <a href="https://www.sciencedirect.com/science/article/pii/S2772442522000466" target="_blank">[Link - Open Access]</a>     
* Persistence in factor-based supervised learning models, <br/>  <span style="color:#3B60A2">**Journal of Finance & Data Science**</span>, Vol. 8 (2022), pp. 12-34 <a href="https://www.sciencedirect.com/science/article/pii/S2405918821000143" target="_blank">[Link - Open Access]</a>  <a href="http://www.gcoqueret.com/horizons.html" target="_blank">[Material]</a>   
* Approximate NORTA simulations for virtual sample generation, <br/>   <span style="color:#3B60A2">**Expert Systems With Applications**</span>, Vol. 73 (2017), pp. 69-81 <a href="https://www.sciencedirect.com/science/article/pii/S0957417416307096" target="_blank">[Link]</a>    
 
</details>

<br2>


<details>
  <summary>**STANDARD PORTFOLIO CHOICE**</summary>

* Training trees on tails with applications to portfolio choice, <br/>   <span style="color:#3B60A2">**Annals of Operations Research**</span>, Vol. 288 (2020), pp. 181-221 (with T. Guida) <a href="https://link.springer.com/article/10.1007/s10479-020-03539-2" target="_blank">[Link]</a>   <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3403009" target="_blank">[Working paper]</a> 
<a href="http://www.gcoqueret.com/tot.html" target="_blank">[Material]</a>   
* Characteristics-based portfolio choice with leverage constraints, <br/>   <span style="color:#3B60A2">**Journal of Banking and Finance**</span>, Vol. 70 (2016), pp. 23-37 (with M. Ammann and J-P. Schade) <a href="https://www.sciencedirect.com/science/article/pii/S0378426616300516" target="_blank">[Link]</a> <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2736324" target="_blank">[Working paper]</a>   
* Diversified minimum-variance portfolios, <br/>   <span style="color:#3B60A2">**Annals of Finance**</span>, Vol. 11, No. 2 (2015), pp. 221-241 <a href="https://link.springer.com/article/10.1007%2Fs10436-014-0253-x" target="_blank">[Link]</a>    

</details>
 
 
<br2> 
 
<details>
  <summary>**PROBABILITY & STATISTICS** (older work)</summary>

* On the distribution of the supremum of the spectrally negative stable process with drift, <br/>  <span style="color:#3B60A2"> **Statistics & Probability Letters**</span>, Vol. 107 (2015), pp. 333-340 <a href="https://www.sciencedirect.com/science/article/pii/S0167715215003314" target="_blank">[Link]</a>     
* Second order risk aggregation with the Bernstein copula, <br/>  <span style="color:#3B60A2"> **Insurance: Mathematics and Economics**</span>, Vol. 58 (2014), pp. 150-158 <a href="https://www.sciencedirect.com/science/article/pii/S0167668714000882" target="_blank">[Link]</a>    
* Meromorphic Levy-Khintchine exponents with poles of order two, <br/>  <span style="color:#3B60A2"> **Communications on Stochastic Analysis**</span>, Vol. 7, No. 2 (2013), pp. 179-198  <a href="https://digitalcommons.lsu.edu/cosa/vol7/iss2/1/" target="_blank">[Link]</a>  
* Approximation of probabilistic Laplace transforms and their inverses, <br/>  <span style="color:#3B60A2"> **Communications in Applied Mathematics and Computational Science**</span>, Vol. 7, No. 2 (2012), pp. 231-246  <a href="https://msp.org/camcos/2012/7-2/p03.xhtml" target="_blank">[Link]</a>   

</details>

<br2>

<details>
  <summary>**WINE BUSINESS** (older work)</summary>

* Herding behavior among wine investors, <span style="color:#3B60A2">**Economic Modelling**</span>, Vol. 68 (2018), pp. 318-328 (with B. Aytac and C. Mandou) <a href="https://www.sciencedirect.com/science/article/pii/S0264999317301001" target="_blank">[Link]</a>    
* Optimal wine pricing for restaurants, <span style="color:#3B60A2">**Journal of Wine Economics**</span>, Vol. 10, No. 2 (2015), pp. 204-224 <a href="https://www.cambridge.org/core/journals/journal-of-wine-economics/article/optimal-wine-pricing-for-restaurants/A3A972D73E0785CE8E6A606470FC0A0E" target="_blank">[Link]</a>      

</details>




_____ 

### <font color="#9AAD98">**In the Practitioner Press**</font> 


<details>
  <summary>**SUSTAINABLE INVESTING**</summary>

* Cross-Asset Climate Betas, <br> <span style="color:#3B60A2">**Journal of Portfolio Management**</span>, Forthcoming (2025), pp. xxx-xxx (with JC Bertrand, N. McLoughlin and S. Mesnard) <a href="https://www.pm-research.com/content/iijpormgmt/50/5/238" target="_blank">[Link]</a> <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5073529" target="_blank">[Working Paper]</a>    
* The impact of climate change risk on long-term asset allocation, <br> <span style="color:#3B60A2">**Journal of Portfolio Management**</span>, Vol. 50, No. 5 (2024), pp. 238-263 (with JC Bertrand, N. McLoughlin and S. Mesnard) <a href="https://www.pm-research.com/content/iijpormgmt/50/5/238" target="_blank">[Link]</a> <a href="papers/climate_risk_alloc.pdf" target="_blank">[Working Paper]</a>    
* International market exposure to sovereign ESG, <br/> <span style="color:#3B60A2">**Journal of Sustainable Finance & Investment**</span>, Vol. 14, No. 4, (2024), pp 968-987, (with C. Morgenstern & J. Kelly) <a href="https://www.tandfonline.com/doi/full/10.1080/20430795.2022.2148817" target="_blank">[Open Access]</a> <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4138136" target="_blank">[Working Paper]</a>   
* Tuning trend following strategies with macro ESG data, <br/> <span style="color:#3B60A2">**Journal of Impact & ESG Investing**</span>, Vol. 2, No. 2 (2021), pp. 117-136 (with C. Morgenstern & J. Kelly) <a href="https://jesg.pm-research.com/content/early/2021/10/25/jesg.2021.1.032" target="_blank">[Link]</a>  

</details>

<br2>


<details>
  <summary>**QUANTITATIVE FINANCE**</summary>

* Interpretable supervised portfolios, <br> 
<span style="color:#3B60A2">**Journal of Financial Data Science**</span>, Vol. 6, No. 2, pp. 10 - 34 (with G. Chevalier & T. Raffinot): <a href="https://www.pm-research.com/content/iijjfds/6/2/10" target="_blank">[Link]</a> <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4230955" target="_blank">[Working Paper]</a>    
* Supervised portfolios, <br> <span style="color:#3B60A2">**Quantitative Finance**</span>, Vol. 22, No. 12 (2022), pp. 2275-2295 (with G. Chevalier & T. Raffinot): 
<a href="https://www.tandfonline.com/doi/abs/10.1080/14697688.2022.2122543" target="_blank">[Link]</a>
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3954109" target="_blank">[Working Paper]</a> - 
<a href="https://colab.research.google.com/drive/1yrhuV5i_o2g0Ju-xJEyONR5s2PFqyk3k" target="_blank">[notebook]</a>   
* Stock-specific sentiment and return predictability, <br/> <span style="color:#3B60A2">**Quantitative Finance**</span>, Vol. 20, No. 9 (2020), pp. 1531-1551 <a href="https://www.tandfonline.com/doi/full/10.1080/14697688.2020.1736314" target="_blank">[Link]</a> <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3248925" target="_blank">[Working paper]</a>   
* Machine learning in systematic equity allocation: a model comparison, <br/> <span style="color:#3B60A2">**Wilmott Magazine**</span>, Vol. 2018, Issue 98 (2018), pp. 24-33 (with T. Guida) <a href="https://onlinelibrary.wiley.com/doi/abs/10.1002/wilm.10719" target="_blank">[Link]</a>      
* Equity portfolios with improved liability-hedging benefits, <br/>   <span style="color:#3B60A2">**Journal of Portfolio Management**</span>, Vol. 43, No. 2 (Winter 2017), pp. 37-49 (with L. Martellini and V. Milhau) <a href="https://jpm.iijournals.com/content/43/2/37" target="_blank">[Link]</a>    

</details>

_____ 


### <font color="#9AAD98">**Book Chapters**</font> 
- Enhancing Environment-driven Portfolios with Traditional Factors, In **Climate and Sustainable Investing** edited by E. Jurczenko, 2023, (with J., Frey-Skött, C. Morgenstern, J. Kelly, B. Österberg, S. Stiernegrip)   
- Ensemble learning applied to quant equity: gradient boosting in a multifactor framework, In **Big Data and Machine Learning in Quantitative Investment** edited by T. Guida, 2018 (with T. Guida)    

 
_____ 


### <font color="#9AAD98">**Book Review**</font> 
Machine Learning in Finance: From Theory to Practice (by Dixon, Halperin and Bilokon), <span style="color:#3B60A2">**Quantitative Finance**</span>, 2020  <a href="https://www.tandfonline.com/doi/full/10.1080/14697688.2020.1828609" target="_blank">[Link]</a>

 

_____ 


### <font color="#9AAD98">**Permanent Working Papers**</font>   
* Forking paths in empirical studies: <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3999379" target="_blank">SSRN</a> -                   <a href="https://www.gcoqueret.com/files/misc/forking_paths.html" target="_blank">R Notebook (first study)</a>   <a href="https://www.gcoqueret.com/files/misc/forking_paths2.html" target="_blank">R Notebook (second study)</a>   
* Boosting ESG-Based Optimization With Asset Pricing Characteristics, 2021 (with J., Frey-Skött, C. Morgenstern, J. Kelly, B. Österberg, S. Stiernegrip) <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3877242" target="_blank">[SSRN]</a>   
* Stock returns and the cross-section of characteristics: a tree-based approach, 2018 (with T. Guida)  <a href="papers/TAPA.pdf" target="_blank">[PDF]</a>    
* Active allocation to smart factor indices, 2015 (with N. Amenc and L. Martellini) - Scientific Beta Research Paper <a href="papers/active_allocation_timing.pdf" target="_blank">[PDF]</a>     
* Estimation of covariance matrices for portfolio optimization, 2013 (with V. Milhau) - Scientific Beta Research Paper <a href="papers/Estim_cov.pdf" target="_blank">[PDF]</a>    
* Equity portfolios with improved liability-hedging benefits - Long Version  (with R. Deguest, L. Martellini and V. Milhau)  <a href="papers/OTPP.pdf" target="_blank">[PDF]</a>    
* Risk aggregation with the generalized logistic distribution, 2013 <a href="papers/Logistic.pdf" target="_blank">[PDF]</a>  
* Pricing exotic options in the Finite Moment Log-Stable model, 2012 <a href="papers/FMLS.pdf" target="_blank">[PDF]</a>  


_____

### <font color="#9AAD98">**Research presentations**</font>

* Explaining green returns (2022) <a href="files/SLIDES/Explaining_green_returns.pdf" target="_blank">[pdf]</a>   
* Advances in asset pricing (2020) <a href="files/SLIDES/AAP/AAP.html" target="_blank">[html]</a>   

_____ 


### <font color="#9AAD98">**Academic profiles**</font>
<a href="http://orcid.org/0000-0002-1596-4086" target="_blank">ORCID</a> &emsp;  <a href="https://www.researchgate.net/profile/Guillaume_Coqueret" target="_blank">Researchgate</a> &emsp;  <a href="https://publons.com/researcher/1352687/guillaume-coqueret" target="_blank">Publons</a>    
  
